# Generated by Django 4.1 on 2023-03-23 17:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/product_images'), upload_to='product_images'),
        ),
    ]
