# Generated by Django 4.2 on 2023-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('new_arrivals', 'New Arrivals')], max_length=20, null=True),
        ),
    ]
